name: Waka Readme

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  schedule:
    - cron: '0/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          COMMIT_MESSAGE: Updated the Readme
          SHOW_PROJECTS: "True"
          SHOW_LINES_OF_CODE: "True"
